Começo dos dois primeiros reports e reorganização em read_raw, read_ready e transform
parlametria/relatorio-reacao-legislativo-ao-executivo pull request #9
Opened 2020-12-10 21:31 UTC by nazareno

2020-12-10 22:48 UTC, gileadekelvin requested changes

2020-12-10 22:48 UTC, gileadekelvin commented on code/read_ready.R
> +      is_parlamentar = col_logical(),
```suggestion
```
As colunas em_exercicio e is_parlamentar não existem no csv de autorias-detalhes.csv
```
Warning message:
The following named parsers don't match the column names: em_exercicio, is_parlamentar 
```

2020-12-10 22:48 UTC, gileadekelvin commented on code/transform.R
> +    proposicoes = read_csv(
Vale a pena um read_proposicoes_raw?

2020-12-11 21:39 UTC, nazareno commented on code/transform.R
> +    proposicoes = read_csv(
Boa

2020-12-11 21:43 UTC, nazareno commented on code/transform.R
> +    proposicoes = read_csv(
Criei

2020-12-11 21:44 UTC, merged